---
title: "model"
author: "Izzy Beers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(knitr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(scorecard)
library(stringr)
source('nfl_model_functions.R')
```

```{r}

new_passing_data = readRDS('data/model_ready_passing_train_df.rds')
new_rushing_data = readRDS('data/model_ready_rushing_train_df.rds')
new_receiving_data = readRDS('data/model_ready_receiving_train_df.rds')
new_touchdown_data = readRDS('data/model_ready_touchdown_train_df.rds')
new_passing_data_test = readRDS('data/model_ready_passing_test_df.rds')
new_rushing_data_test = readRDS('data/model_ready_rushing_test_df.rds')
new_receiving_data_test = readRDS('data/model_ready_receiving_test_df.rds')
new_touchdown_data_test = readRDS('data/model_ready_touchdown_test_df.rds')

passing_data_column_categories = readRDS('data/passing_data_column_categories.rds')
rushing_data_column_categories = readRDS('data/rushing_data_column_categories.rds')
receiving_data_column_categories = readRDS('data/receiving_data_column_categories.rds')
touchdown_data_column_categories = readRDS('data/touchdown_data_column_categories.rds')
```


```{r}

model_manual_remove = c('min_year', 'max_year')
t1 = Sys.time()
all_tunings_passing = rbind()
optimal_models_passing = list()
for(p in 1:length(new_passing_data))
{
  df = new_passing_data[[p]] %>% select(-any_of(c(passing_data_column_categories$basic_cols, model_manual_remove, 'Passing_Yds')))
  response = names(new_passing_data)[p]
  print(response)
  tuning_and_models = run_gbm(df, response, t_per_s = c(1000,500), i_range = 5, s_range = c(0.01, 0.05), n_range = 10, b_range = 0.5)
  tuning = tuning_and_models[[1]]  %>% mutate(Response = response, prevalence = mean(df[,response]))
  models = tuning_and_models[[2]]
  optimal_tuning_index = which.max(tuning$precision)
  optimal_tuning = tuning[optimal_tuning_index,]
  optimal_model = models[optimal_tuning_index]
 optimal_models_passing[[response]] = optimal_model
  all_tunings_passing = rbind(all_tunings_passing, optimal_tuning)
}
saveRDS(all_tunings_passing, 'tunings_and_models/all_tunings_passing.rds')
saveRDS(optimal_models_passing, 'tunings_and_models/passing_models.rds')
Sys.time() - t1
rm(all_tunings_passing)
rm(optimal_models_passing)

t1 = Sys.time()
all_tunings_rushing = rbind()
optimal_models_rushing = list()
for(p in 1:length(new_rushing_data))
{
  df = new_rushing_data[[p]] %>% select(-any_of(c(rushing_data_column_categories$basic_cols, model_manual_remove, 'Rushing_Yds')))
  response = names(new_rushing_data)[p]
  print(response)
  tuning_and_models = run_gbm(df, response, t_per_s = c(1000,500), i_range = 5, s_range = c(0.01, 0.05), n_range = 10, b_range = 0.5) 
  tuning = tuning_and_models[[1]] %>% mutate(Response = response, prevalence = mean(df[,response]))
  models = tuning_and_models[[2]]
  optimal_tuning_index = which.max(tuning$precision)
  optimal_tuning = tuning[optimal_tuning_index,]
  optimal_model = models[optimal_tuning_index]
  optimal_models_rushing[[response]] = optimal_model
  all_tunings_rushing = rbind(all_tunings_rushing, optimal_tuning)
}
saveRDS(all_tunings_rushing, 'tunings_and_models/all_tunings_rushing.rds')
saveRDS(optimal_models_rushing, 'tunings_and_models/rushing_models.rds')
Sys.time() - t1
rm(all_tunings_rushing)
rm(optimal_models_rushing)

t1 = Sys.time()
all_tunings_receiving = rbind()
optimal_models_receiving = list()
for(p in 1:length(new_receiving_data))
{
  df = new_receiving_data[[p]] %>% select(-any_of(c(receiving_data_column_categories$basic_cols, model_manual_remove, 'Receiving_Yds')))
  response = names(new_receiving_data)[p]
  print(response)
  tuning_and_models = run_gbm(df, response, t_per_s = c(1000,500,100), i_range = 5, s_range = c(0.01, 0.05, 0.1), n_range = 10, b_range = 0.5)
  tuning = tuning_and_models[[1]]  %>% mutate(Response = response, prevalence = mean(df[,response]))
  models = tuning_and_models[[2]]
  optimal_tuning_index = which.max(tuning$precision)
  optimal_tuning = tuning[optimal_tuning_index,]
  optimal_model = models[optimal_tuning_index]
  optimal_models_receiving[[response]] = optimal_model
  all_tunings_receiving = rbind(all_tunings_receiving, optimal_tuning)
  
}
saveRDS(all_tunings_receiving, 'tunings_and_models/all_tunings_receiving.rds')
saveRDS(optimal_models_receiving, 'tunings_and_models/receiving_models.rds')
Sys.time() - t1
rm(all_tunings_receiving)
rm(optimal_models_receiving)

t1 = Sys.time()
for(p in 1:length(new_touchdown_data))
{
  df = new_touchdown_data[[p]] %>% select(-any_of(c(touchdown_data_column_categories$basic_cols, model_manual_remove)))
  response = names(new_touchdown_data)[p]
  print(response)
  tuning_and_models = run_gbm(df, response, t_per_s = c(1000,500,100), i_range = 5, s_range = c(0.01, 0.05, 0.1), n_range = 10, b_range = 0.5)
  tuning = tuning_and_models[[1]]  %>% mutate(Response = response, prevalence = mean(df[,response]))
  models = tuning_and_models[[2]]
  optimal_tuning_index = which.max(tuning$precision)
  optimal_tuning_touchdown = tuning[optimal_tuning_index, ]
  optimal_model_touchdown[[response]] = optimal_model
}
saveRDS(optimal_tuning_touchdown, 'tunings_and_models/optimal_tuning_touchdown.rds')
saveRDS(optimal_model_touchdown, 'tunings_and_models/optimal_model_touchdown.rds')
Sys.time() - t1

```

```{r}
passing_model_params = readRDS('tunings_and_models/all_tunings_passing.rds')
passing_models = readRDS('tunings_and_models/passing_models.rds')
for (response in passing_response)
{
  model_params = passing_model_params[passing_model_params$Response == response,]
  model = passing_models[[response]] 
  test = new_passing_data_test[[response]]
  if ("weight" %in% colnames(test))
  {
    test = test %>% rename('player_weight' = 'weight')
  }
  
  test = test %>%
    mutate(across(where(is.character), as.factor))
  
  test <- test %>%
    rename_with(.cols = matches(" "),
                .fn = ~gsub(' ', '_', .x))
  
  test[,response] = as.numeric(as.character(test[,response]))
  
  colnames(test) = gsub("[^A-Za-z0-9_]", "_", colnames(test))
  
  test = test[, !duplicated(colnames(test))] #remove any duplicated column names
  
  preds = predict(model[[1]], test, n.trees = model_params$trees)
  
  actual = test[,response]
  #precision and recall
  pred_class_table = data.frame()
  for (p in seq(0.05,1,0.05))
  {
    pred_classes = ifelse(pred_probs > p, 1, 0)
    precision = (sum(pred_classes == 1 & actual == 1))/(sum(pred_classes == 1))
    recall = (sum(pred_classes == 1 & actual == 1))/(sum(actual == 1))
    pred_class_table = rbind(pred_class_table, c(p, precision, recall))
  }
  colnames(pred_class_table) = c('p', 'precision', 'recall')
  
  buckets = floor(preds*10)/10
  
  sapply(unique(buckets), function(b) mean(actual[buckets == b], na.rm = TRUE))
  
  

}


```
