---
title: "Weekly Bet Cheat Sheet"
output: html_document
params:
  season: 2025
  week: 6
  bettors: 'Testing,Testing2'
  future_games_only: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r}
library(dplyr)
library(httr)
library(rvest)
library(htmltools)
library(lubridate)
library(stringr)
team_lookup_table = read.csv('https://docs.google.com/spreadsheets/d/1DSSz4X-3LLAarRlBRtuMsGJ1hh2FDdVeHJZFdpZGW0A/export?format=csv&gid=0')

survivor_teams = c('Arizona Cardinals', 'Dallas Cowboys')

get_html_content = function(url, max_retries = 3, skip_to_chromote = FALSE, extra_wait = 0) {
  retries = 0
 
for (i in 1:max_retries) {
  if(!skip_to_chromote)
  {
    try_result = try({
      session <- session(url, user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/113.0.0.0 Safari/537.36"))
      page <- read_html(session)
      if(length(html_children(page)) > 0)
      {
        return(page)  # Success — exit function
      } else {
        page = NULL
        stop("Empty content detected — triggering fallback to Chromote")
      }
    }, silent = TRUE)
  }
  
  # If the above failed, try with Chromote
  try_result = try({
    message("Using chromote")
    b <- ChromoteSession$new()
    b$Page$navigate(url)
    Sys.sleep(extra_wait) #if certain sites take a few more seconds to load before pulling result, like nfl's site
    result <- b$Runtime$evaluate("document.documentElement.outerHTML")
    html_content <- result$result$value
    page = read_html(html_content)
    
    return(page)  # Success — exit function
  })

  if (!is.null(try_result)) return(try_result)
      
    # Only wait if both methods failed
    wait_time <- runif(1, 2, 4)
    message(paste("Both methods failed. Waiting", round(wait_time, 1), "seconds before retrying..."))
    Sys.sleep(wait_time)
}


stop(paste(max_retries, "attempts failed to retrieve", url))

}

clean_names = function(name)
{
  return(tolower(name) %>% str_remove_all("[[:punct:]]+") %>% str_remove("\\b(jr|sr|i{1,3}|iv|v|vi{1,3}|ix|x|xi{1,3})\\b") %>% str_squish() %>% trimws())
}




```


```{r}


depth_charts = read.csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTyIaWWovW2YUP1-JxYpg9ZHpF7a2i_7AEVan5ptaBBiwj6gwYp0STpE8HvYILR190HTrOFt2GMyUqn/pub?gid=594515538&single=true&output=csv') %>% select(Player, No, Position)


bettors = strsplit(params$bettors, ',') %>% unlist()
placed_bets = read.csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTyIaWWovW2YUP1-JxYpg9ZHpF7a2i_7AEVan5ptaBBiwj6gwYp0STpE8HvYILR190HTrOFt2GMyUqn/pub?gid=95780958&single=true&output=csv') %>% filter(Week == params$week & Season == params$season & Bettor %in% bettors) %>% select(Bettor, Player,Bet_Type, Label, Team, Opp, Gametime, Timeslot) %>%
  mutate(clean = clean_names(Player)) %>%
  inner_join(depth_charts, join_by('clean' == 'Player')) %>%
  select(-clean)

if(params$future_games_only)
{
  placed_bets = placed_bets %>% filter(Gametime >= Sys.time() - 120)
}


url = paste0("https://www.pro-football-reference.com/years/", params$season, '/games.htm')
schedule_html = get_html_content(url = url)
schedule_table_node = schedule_html %>% html_node('table#games')
if (!inherits(schedule_table_node, "xml_missing"))
{
  schedule_table = schedule_table_node %>% html_table(fill = TRUE)
} else {
   schedule_table = NULL
}
games= schedule_table[schedule_table$Week == params$week,c(1,2,3,4,5,7)]  %>%
  mutate(Time = format(strptime(Time, "%I:%M%p"), "%H:%M"),
         posix_timestamp_game = as.POSIXct(paste(Date, Time), tz = "America/New_York")) %>%
  mutate(time_parsed = parse_date_time(Time, orders = c("I:Mp","I:M p","H:M")),
         Timeslot = paste(Day, case_when(hour(time_parsed) < 11 ~ 'Morning',
                                         hour(time_parsed) < 15 ~ 'Early Window',
                                         hour(time_parsed) < 19 ~ 'Late Window',
                                         TRUE ~ 'Night')))

if(length(survivor_teams) > 0)
{
  survivor_team_df = survivor_teams %>% data.frame()
  colnames(survivor_team_df) = 'Survivor_Team'
  survivor_team_df = survivor_team_df %>% inner_join(games %>% rename('Opp' = `Loser/tie`), join_by('Survivor_Team' == `Winner/tie`)) %>%
    rbind(survivor_team_df %>% inner_join(games %>% rename('Opp' = `Winner/tie`), join_by('Survivor_Team' == `Loser/tie`))) %>%
   select(Survivor_Team, Opp, Timeslot)
} else{
  survivor_team_df = NULL
}
    

```


```{r, results = 'asis'}

for (t in games %>% arrange(posix_timestamp_game) %>% select(Timeslot) %>% distinct() %>% pull())
{
  this_timeslot = placed_bets %>% filter(Timeslot == t) %>%
    left_join(team_lookup_table %>% select(FullName, Team) %>% rename('TeamFullName' = 'FullName'), join_by('Team')) %>%
       left_join(team_lookup_table %>% select(FullName, Team) %>% rename('OppFullName' = 'FullName'), join_by('Opp' == 'Team'))
  this_timeslot = this_timeslot %>% mutate(game = paste(pmin(TeamFullName, OppFullName),
                                                        pmax(TeamFullName, OppFullName),
                                                        sep = " - ")) %>%
    arrange(Team)
  
  if(nrow(this_timeslot) > 0)
  {
    print(tags$h1(t))
    
    if(!is.null(survivor_team_df) && nrow(survivor_team_df)> 0)
    {
      survivors_this_timeslot = survivor_team_df %>% filter(Timeslot == t)
      if(nrow(survivors_this_timeslot) > 0)
      {
        print(tags$h3(paste('Survivor Games:')))
        for(s in 1:nrow(survivors_this_timeslot))
        {
          print(tags$p(paste0(survivors_this_timeslot$Survivor_Team[s], ' (vs. ', survivors_this_timeslot$Opp[s], ')')))
        }
      }
    }
    for(g in unique(this_timeslot$game))
    {
      print(tags$h3(paste(g, 'Bets')))
      this_game = this_timeslot %>% filter(game == g)
      players_this_game = this_game %>% group_by(Player, Bet_Type, Label) %>% summarise(Bettors = paste(Bettor, collapse = ","), TeamFullName = max(TeamFullName), Number = max(No), Position = max(Position)) %>% arrange(TeamFullName)
      for(p in 1:nrow(players_this_game))
      {
        print(tags$p(paste0(ifelse(length(bettors) > 1, paste0(players_this_game$Bettors[p], ": "), ''), players_this_game$Player[p], ' (', players_this_game$TeamFullName[p],', ', players_this_game$Position[p], ' #', players_this_game$Number[p], ') -- ', players_this_game$Bet_Type[p], ifelse(players_this_game$Bet_Type[p] == 'Anytime TD Scorer', '', players_this_game$Label[p]))))
      }
    }
  }
}


```

