---
title: "Player Stats By Season"
author: "Izzy Beers"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}


player_gamelogs = readRDS('saved_data_files/player_gamelogs.rds')

basic_cols = c('player_id', 'Name', 'Position', 'Month', 'Gtm', 'Week', 'day_of_week', 'Date', 'Team', 'Game_Location', 'Opp', 'Result', 'Season')
team_cols = c('Win', 'Differential')
in_season_calculation_columns = colnames(player_gamelogs)[which(str_detect(colnames(player_gamelogs), 'Cumulative_|Avg_|Last3_|Median_|Max_|Min_|_Per_|SD_|Lag|This_Season|Pct'))]
columns_to_use = setdiff(colnames(player_gamelogs), c(basic_cols, team_cols, in_season_calculation_columns))


t1 = Sys.time()
grouped_table = player_gamelogs %>% select(player_id, Name, Season, Team, all_of(columns_to_use)) %>%
  group_by(player_id, Name, Season) %>%
   summarise(
     Teams = paste(Team, collapse = ","),
     across(
    all_of(columns_to_use),
    .fns = list(
      sum = ~sum(.x, na.rm = TRUE),
      mean = ~mean(.x, na.rm = TRUE),
      median = ~median(.x, na.rm = TRUE),
      max = ~max(.x, na.rm = TRUE),
      min = ~min(.x, na.rm = TRUE),
      sd = ~sd(.x, na.rm = TRUE)
    ),
    .names = "{.col}_{.fn}"
  ), .groups = "drop") 
Sys.time() - t1


```

```{r}

#Just like with the weekly gamelogs data, we will do the following:
#1. For stats that are 0/1 (like Active, Game Started), a median, sd, max, and min don't make sense. For these, we will just keep the cumulative amount and the mean.
#2. For stats with very low medians, like number of touchdowns (which are mostly 0 or 1, and in very few cases at least 2), no reason to have min or median. Only cumulative, mean, max, and maybe sd are useful.
#3. Any columns that are all NA or only have one unique value will be removed.

source('global.R')
uninformative_stats_results = remove_uninformative_stats(df = player_gamelogs,
                                                         column_list = columns_to_use)


columns_0_1 = uninformative_stats_results[[2]]
low_medians = uninformative_stats_results[[3]]

player_seasonal_stats = grouped_table

if(length(columns_0_1) > 0)
{
  player_seasonal_stats = player_seasonal_stats %>% conditionally_remove(colnames(grouped_table)[which(colnames(grouped_table) %in% paste0(columns_0_1, '_sd'))])
  player_seasonal_stats = player_seasonal_stats %>% conditionally_remove(colnames(grouped_table)[which(colnames(grouped_table)%in% paste0(columns_0_1, '_median'))])
  player_seasonal_stats = player_seasonal_stats %>% conditionally_remove(colnames(grouped_table)[which(colnames(grouped_table) %in% paste0(columns_0_1, '_max'))])
  player_seasonal_stats = player_seasonal_stats %>% conditionally_remove(colnames(grouped_table)[which(colnames(grouped_table) %in% paste0(columns_0_1, '_min'))])
}
if(length(low_medians) > 0)
{
  player_seasonal_stats = player_seasonal_stats %>% conditionally_remove(colnames(grouped_table)[which(colnames(grouped_table) %in% paste0(low_medians, '_median'))])
  player_seasonal_stats = player_seasonal_stats %>% conditionally_remove(colnames(grouped_table)[which(colnames(grouped_table) %in% paste0(columns_0_1, '_max'))])
}



player_seasonal_stats = player_seasonal_stats %>%
  rename('Pct_GS' = 'GS_mean',
         'Pct_Active' = 'Active_mean') %>%
  mutate(Passing_Comp_Pct = Passing_Cmp_sum / Passing_Att_sum,
         Receiving_Catch_Pct = Receiving_Rec_sum / Receiving_Tgt_sum,
         Passing_Yds_Per_Completion = Passing_Yds_sum / Passing_Cmp_sum,
         Passing_Yds_Per_Attempt = Passing_Yds_sum / Passing_Att_sum,
         Rushing_Yds_Per_Attempt = Rushing_Yds_sum / Rushing_Att_sum,
         Rushing_1D_Per_Attempt = Rushing_1D_sum / Rushing_Att_sum,
         Rushing_YAC_Per_Attempt = Rushing_YAC_sum / Rushing_Att_sum,
         Receiving_Yds_Per_Tgt = Receiving_Yds_sum / Receiving_Tgt_sum,
         Receiving_Yds_Per_Rec = Receiving_Yds_sum / Receiving_Rec_sum,
         Receiving_1D_Per_Tgt = Receiving_1D_sum / Receiving_Tgt_sum,
         Receiving_1D_Per_Rec = Receiving_1D_sum / Receiving_Rec_sum,
         Receiving_YBC_Per_Tgt = Receiving_YBC_sum / Receiving_Tgt_sum,
         Receiving_YBC_Per_Rec = Receiving_YBC_sum / Receiving_Rec_sum,
         Receiving_YAC_Per_Tgt = Receiving_YAC_sum / Receiving_Tgt_sum,
         Receiving_YAC_Per_Rec = Receiving_YAC_sum / Receiving_Rec_sum,
         Pct_Offensive_Snaps = `Snap Counts_OffSnp_sum` / Total_Team_Off_Snaps_sum,
         Pct_ST_Snaps = `Snap Counts_STSnp_sum` / Total_Team_ST_Snaps_sum)

player_seasonal_stats = player_seasonal_stats %>% conditionally_remove(colnames(player_seasonal_stats)[str_detect(colnames(player_seasonal_stats), '_sum')])

saveRDS(player_seasonal_stats, 'saved_data_files/player_end_of_season_summary_stats.rds')

```
