---
title: "get_weather_data"
author: "Izzy Beers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, waning = FALSE, message = FALSE)
```

```{r}
source('global.R')
library(tidyr)
library(purrr)





t1 = Sys.time()
games = readRDS('saved_data_files/team_gamelogs.rds') %>%
  mutate(Stadium = ifelse(Game_Location == 'Away', Opp, Team),
         Date = paste0(Season, '-', str_pad(match(word(Date, 1), month.name), 2, 'left', '0'), '-', str_pad(word(Date, 2), 2, 'left', '0'))) %>%
  select(Season, Week, Date, Time_of_Day, Stadium, Team, Opp) %>% distinct() %>%
  left_join(team_lookup_table %>%
              select(Team, Grass_Type, Roof, Altitude, Stadium_Capacity, Loudest_Stadiums, Coast, weather_station_link) %>% rename('Stadium_Coast' = 'Coast'), join_by('Stadium' == 'Team')) %>%
  left_join(team_lookup_table %>%
              select(Team, Coast, Conference, Division, Used_To_Cold, Used_To_Hot, Roof, Grass_Type) %>%
              rename('Home_Roof' = 'Roof', 'Home_Grass_Type' = 'Grass_Type'),
            join_by('Team' == 'Team')) %>%
  left_join(team_lookup_table %>%
              select(Team, Coast, Conference, Division, Used_To_Cold, Used_To_Hot) %>%
              rename_with(~ paste0("Opp_",.), .cols = -Team),
            join_by('Opp' == 'Team')
  ) %>%
  mutate(Same_Division = ifelse(Division == Opp_Division, 1, 0),
         Same_Conference = ifelse(Conference == Opp_Conference, 1, 0),
         Long_Travel = ifelse(Stadium_Coast != '' & Coast != '' & Stadium_Coast != Coast, 1, 0),
         Familiar_Grass_Type = ifelse(Grass_Type == Home_Grass_Type, 1, 0),
         Familiar_Roof_Type = ifelse(Roof == Home_Roof, 1, 0)) %>%
  select(-Home_Grass_Type, -Home_Roof)

nondome_games_with_weather = games %>% filter(Roof == 'Open') %>%
  select(Season, Week, Date, Time_of_Day, Stadium, weather_station_link) %>% distinct() %>%
  mutate(weather = pmap(list(Date, Time_of_Day, weather_station_link, Stadium),
                        ~ get_weather(..1, ..2, station_link = ..3, stadium = ..4))) %>%
  unnest_wider(weather, names_sep = "_")
  
games_with_weather = games %>%
  left_join(nondome_games_with_weather %>% select(Stadium, Week, Season, weather_approx_temperature, weather_approx_visibility, weather_approx_wind_speed), join_by('Stadium' == 'Stadium', 'Week' == 'Week', 'Season' == 'Season')) %>%
  select(-weather_station_link, -Date, -Time_of_Day, -Opp_Coast, -Opp_Conference, -Opp_Division) %>%
  arrange(Season, Week)

Sys.time() - t1


saveRDS(games_with_weather, 'saved_data_files/weather_and_stadium_data.rds')







```
