---
title: "get_player_list"
date: '`r Sys.time()`'
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(stringr)
library(dplyr)
source('global.R')
```

##First, pull the master list of players and extract their basic info like name, position, and active years
```{r}
player_df = rbind()

year_cutoff = 2020 #we can use some retired players in our training data, but how far back do we want to go? This is the filter cutoff for a player's max_year.
  
for (let in LETTERS)
{
  print(let)
  player_list = get_html_content(url = paste0("https://www.pro-football-reference.com/players/",let))
  if (any(str_detect(player_list %>% html_nodes("p") %>% as.character(), 'block traffic')))
  {
    print("Site detected scraping. Try again in one hour.")
    Sys.sleep(65*60)
    player_list = get_html_content(url = paste0("https://www.pro-football-reference.com/players/",let))
  }
  
  player_list_content = player_list %>% html_nodes(".section_content#div_players")
  total_info = player_list_content %>% html_nodes("p") %>% html_text(trim = TRUE)
  years = str_extract(total_info, '[0-9]+-[0-9]+')
  min_year = sapply(strsplit(years, "-"), function(x) x[1])
  max_year = sapply(strsplit(years, "-"), function(x) x[2])
  positions = gsub('\\(|\\)','',str_extract(total_info, "\\(.*\\)"))
  names = gsub(' \\(', '', str_extract(total_info, '.+\\('))
  links = player_list_content %>% html_nodes("a") %>% html_attr("href")
  
  df = data.frame(names, positions, min_year, max_year,links) %>% mutate(min_year = as.numeric(min_year), max_year = as.numeric(max_year))
  
  df_filtered = df %>% filter(max_year >= year_cutoff)
  
  player_df = rbind(player_df, df_filtered)
  wait = runif(1,5,10)
  Sys.sleep(wait)
}

for (i in 1:length(strsplit(player_df$positions, '-|/|,')))
{                            
 x = strsplit(player_df$positions, '-|/|,')[i]
 y = x[[1]]
}

players_with_positions = player_df %>% filter(positions != '')

receiving_positions <- c("WR", "SE", "FL", "TE", "WB", "RB", "HB", "FB", "TB")

rushing_positions <- c("RB", "HB", "TB", "FB", "QB", "WR", "WB", "TE")

passing_positions <- c("QB")

players_with_positions$receiving_model = sapply(strsplit(players_with_positions$positions, '-|/|,'), function(x) ifelse(any(x[[1]] %in% receiving_positions), 1, 0))
players_with_positions$rushing_model = sapply(strsplit(players_with_positions$positions, '-|/|,'), function(x) ifelse(any(x[[1]] %in% rushing_positions), 1, 0))
players_with_positions$passing_model = sapply(strsplit(players_with_positions$positions, '-|/|,'), function(x) ifelse(any(x[[1]] %in% passing_positions), 1, 0))

model_players = players_with_positions %>% filter(receiving_model == 1 | rushing_model == 1 | passing_model == 1)

head(model_players,10)
```

##Next, pull the bio for each player by following the links for each player:

```{r}

player_bios = rbind()

for(i in 1:nrow(model_players))
{
  print(i)
  df = get_player_bio(player_row = model_players[i,])
  if (any(str_detect(player_list %>% html_nodes("p") %>% as.character(), 'block traffic')))
  {
    print("Site detected scraping. Try again in one hour.")
    Sys.sleep(65*60)
    df = get_player_bio(player_row = model_players[i,])
  }
  player_bios =  rbind(player_bios, cbind(model_players[i,], df %>% select(-name)))
  wait = runif(1,2,4) #too many requests too quickly will cause site to block request. Staggering the waiting time also helps make us look human.
  Sys.sleep(wait)
}

```

```{r}
player_bios$player_id = 1:nrow(player_bios) 

saveRDS(player_bios, 'saved_data_files/player_bios.rds')
```                                         
                                               
```


